/*!
* \file   src/chaboche_PoissonRatio-castem.cxx
* \brief  this file implements the chaboche_PoissonRatio MaterialLaw.
*         File generated by tfel version 3.4.1
 */

#include<algorithm>
#include<iterator>
#include<iostream>
#include<sstream>
#include<fstream>
#include<cstring>
#include<cstdlib>
#include<string>
#include<vector>
#include<cmath>
#include"chaboche_PoissonRatio-castem.hxx"

#ifdef __cplusplus
extern "C"{
#endif /* __cplusplus */

MFRONT_SHAREDOBJ const char *
chaboche_PoissonRatio_args[1] = {"xnu"};

MFRONT_SHAREDOBJ unsigned short
chaboche_PoissonRatio_nargs = 1u;

MFRONT_SHAREDOBJ const char* 
chaboche_PoissonRatio_build_id = "";

MFRONT_SHAREDOBJ const char* 
chaboche_PoissonRatio_mfront_ept = "chaboche_PoissonRatio";

MFRONT_SHAREDOBJ const char* 
chaboche_PoissonRatio_tfel_version = "3.4.1";

MFRONT_SHAREDOBJ const char *
chaboche_PoissonRatio_mfront_interface = "Castem";

MFRONT_SHAREDOBJ unsigned short chaboche_PoissonRatio_mfront_mkt = 0u;

MFRONT_SHAREDOBJ const char *
chaboche_PoissonRatio_src = "chaboche.mfront";

MFRONT_SHAREDOBJ double
chaboche_PoissonRatio(const double * const castem_params)
{
using namespace std;
typedef double real;
const double xnu = *(castem_params);
real res;
res = xnu;
return res;
} // end of chaboche_PoissonRatio

#ifdef __cplusplus
} // end of extern "C"
#endif /* __cplusplus */

