/*!
* \file   src/chaboche_YoungModulus-castem.cxx
* \brief  this file implements the chaboche_YoungModulus MaterialLaw.
*         File generated by tfel version 3.4.1
 */

#include<algorithm>
#include<iterator>
#include<iostream>
#include<sstream>
#include<fstream>
#include<cstring>
#include<cstdlib>
#include<string>
#include<vector>
#include<cmath>
#include"chaboche_YoungModulus-castem.hxx"

#ifdef __cplusplus
extern "C"{
#endif /* __cplusplus */

MFRONT_SHAREDOBJ const char *
chaboche_YoungModulus_args[1] = {"xyoung"};

MFRONT_SHAREDOBJ unsigned short
chaboche_YoungModulus_nargs = 1u;

MFRONT_SHAREDOBJ const char* 
chaboche_YoungModulus_build_id = "";

MFRONT_SHAREDOBJ const char* 
chaboche_YoungModulus_mfront_ept = "chaboche_YoungModulus";

MFRONT_SHAREDOBJ const char* 
chaboche_YoungModulus_tfel_version = "3.4.1";

MFRONT_SHAREDOBJ const char *
chaboche_YoungModulus_mfront_interface = "Castem";

MFRONT_SHAREDOBJ unsigned short chaboche_YoungModulus_mfront_mkt = 0u;

MFRONT_SHAREDOBJ const char *
chaboche_YoungModulus_src = "chaboche.mfront";

MFRONT_SHAREDOBJ double
chaboche_YoungModulus(const double * const castem_params)
{
using namespace std;
typedef double real;
const double xyoung = *(castem_params);
real res;
res = xyoung;
return res;
} // end of chaboche_YoungModulus

#ifdef __cplusplus
} // end of extern "C"
#endif /* __cplusplus */

